
spring:
  application:
    name: stock-strategy-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:strategyuser}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Let Flyway manage schema creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

loader:
  symbolXlsxPath: ${LOADER_SYMBOL_XLSX_PATH:${user.dir}/data/Nasdaq100.xlsx}
  symbolTxtPath: ${LOADER_SYMBOL_TXT_PATH:${user.dir}/data/nasdaq100.txt}
  dataDirPath: ${LOADER_DATA_DIR_PATH:${user.dir}/data/yahoo}
  # !!! Data download nefunguje NEZAPINAT!!!. Provadi se projektem download-data (Python)
  downloadMissingData: ${LOADER_DOWNLOAD_MISSING_DATA:false}
  downloadMissingBeforeData: ${LOADER_DOWNLOAD_MISSING_BEFORE_DATA:false}
  downloadMissingAfterData: ${LOADER_DOWNLOAD_MISSING_AFTER_DATA:false}
